#!/usr/bin/env python3
import argparse
import os
import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
from pu_ray.utils import KNN, farthest_point_sampling


def main(args):
    torch.cuda.empty_cache()
    torch.autograd.set_detect_anomaly(True)
    torch.multiprocessing.set_start_method("spawn")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(device)

    try:
        os.mkdir(f"{args.input}_query_points")
    except FileExistsError:
        None

    file_li = os.listdir(args.input)
    for idx, f in tqdm(enumerate(file_li)):
        try:
            input_df = pd.read_csv(f"{args.input}/{f}", names=["x", "y", "z"])
            input_df = input_df[input_df["x"] > 50000]
            input_df = input_df[input_df.abs()["y"] < 30000]
            input_df = input_df[input_df.abs()["z"] < 30000]
            input_pc = torch.tensor(input_df.sample(frac=1).values).to(device)

            gt_df = pd.read_csv(f"{args.gt}/{f}", names=["x", "y", "z"])
            gt_df = gt_df[gt_df["x"] > 50000]
            gt_df = gt_df[gt_df.abs()["y"] < 30000]
            gt_df = gt_df[gt_df.abs()["z"] < 30000]
            gt_pc = torch.tensor(gt_df.sample(frac=1).values).to(device)
        except IsADirectoryError:
            continue
        print(f)
        if os.path.isfile(f"{args.input}_query_points/{f}"):
            continue

        num_chunks = 256
        while True:
            try:
                input_chunks = torch.chunk(input_pc, num_chunks)

                input_chunks_li = []
                for chunk in input_chunks:
                    input_chunks_li.append(
                        KNN(
                            gt_pc,
                            chunk,
                            1,
                            include_nearest=True,
                            cossim=False,
                            device=device,
                        )[0].squeeze(1)
                    )
                break
            except torch.cuda.OutOfMemoryError:
                num_chunks *= 2

        input_pc = torch.cat(input_chunks_li, 0)

        gt_chunks = torch.chunk(gt_pc, num_chunks)
        knn_std = []
        knn_mean = []
        for chunk in gt_chunks:
            knn_coords, _ = KNN(
                input_pc, chunk, 16, include_nearest=True, cossim=True, device=device
            )
            knn_std.append(torch.std(knn_coords, 1))
            knn_mean.append(torch.mean(knn_coords, 1))

        knn_std = torch.cat(knn_std, 0)
        knn_mean = torch.cat(knn_mean, 0)
        valid_idx = torch.sum(torch.abs(gt_pc - knn_mean) < knn_std * 1.5, 1) == 3

        gt_pc = gt_pc[valid_idx]
        knn_std = knn_std[valid_idx]

        std_avg = torch.mean(knn_std, 0)
        std_std = torch.std(knn_std, 0)
        valid_idx = torch.sum(torch.abs(knn_std - std_avg) < std_std * 1.5, 1) == 3

        query_points = gt_pc[valid_idx]
        query_points = pd.DataFrame(
            query_points.cpu().numpy(),
            columns=["x", "y", "z"],
        )
        query_points = farthest_point_sampling(query_points, len(input_pc) * args.r)[
            ["x", "y", "z"]
        ]

        np.savetxt(f"{args.input}_query_points/{f}", query_points, delimiter=",")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Input point cloud directory path",
    )
    parser.add_argument(
        "--gt",
        type=str,
        help="Ground truth directory path",
    )
    parser.add_argument(
        "--r",
        type=int,
        default=16,
        help="Upsampling rate",
    )

    args = parser.parse_args()

    main(args)
