#!/usr/bin/env python3
import argparse
import sys
import torch
import gc
import pandas as pd
import numpy as np
from tqdm import tqdm
from pu_ray.utils import QueryPointsData, ChamferLoss
from pu_ray.models import QueryPoints
from torch.utils.data import DataLoader
from torch import nn
import torch.optim as optim


def main(args):
    torch.cuda.manual_seed(args.seed)
    torch.cuda.empty_cache()
    torch.autograd.set_detect_anomaly(True)
    torch.multiprocessing.set_start_method("spawn")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(device)

    if args.verbose:
        log_target = sys.stdout
    else:
        log_target = open(f"./log/{args.log}.log", "w")

    # Load the model
    model = nn.DataParallel(QueryPoints(device=device, r=args.r)).to(device)
    print(
        f"Number of parameters: {sum(p.numel() for p in model.parameters() if p.requires_grad)}"
    )

    train_dataset = QueryPointsData(
        args.input,
        args.reference,
        args.gt,
        device=device,
        r=args.r,
    )

    # Train-validation split
    train_dataset, val_dataset = torch.utils.data.random_split(
        train_dataset, [0.8, 0.2]
    )
    # Data loader
    data_loader = DataLoader(
        train_dataset,
        num_workers=0,
        batch_size=1,
        shuffle=True,
        drop_last=True,
    )

    # Data loader
    val_data_loader = DataLoader(
        val_dataset,
        num_workers=0,
        batch_size=1,
        shuffle=True,
        drop_last=True,
    )

    # Loss function
    loss_function = ChamferLoss().to(device)

    # Learning strategy
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-2)
    # scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100, eta_min=1e-3)
    scheduler = optim.lr_scheduler.ExponentialLR(
        optimizer, 0.8, last_epoch=-1, verbose=False
    )

    best = np.inf
    for epoch in range(args.num_epochs):
        # Training
        count = 0
        batch_count = 0
        train_loss = 0.0
        batch_loss = 0.0
        for idx, (input_pc, gt_pc) in tqdm(enumerate(data_loader)):
            # Predict
            output_pc = model(input_pc)

            # Update
            loss = loss_function(output_pc, gt_pc, device=device)

            batch_loss += loss.to(device)
            batch_count += 1

            train_loss += loss
            count += 1

            if (idx + 1) % args.batch_size == 0 or idx == len(data_loader) - 1:
                optimizer.zero_grad()
                batch_loss = batch_loss / batch_count
                batch_loss.backward()
                optimizer.step()

                print(
                    f"Batch # {(idx) // args.batch_size + 1} loss: {batch_loss.item()}"
                )

                batch_loss = 0.0
                batch_count = 0

            # garbage collect
            input_pc = input_pc.detach().cpu()
            gt_pc = gt_pc.detach().cpu()
            output_pc = output_pc.detach().cpu()
            del (
                input_pc,
                gt_pc,
                output_pc,
            )
            gc.collect()
            torch.cuda.empty_cache()

        scheduler.step()

        outstr = f"Epoch {epoch}, Loss: {(train_loss / count)}"
        print(outstr, file=log_target)

        # Validation
        val_count = 0.0
        val_loss = 0.0
        for val_input_pc, val_gt_pc in val_data_loader:
            # Predict
            val_output_pc = model(val_input_pc)

            # Loss calcuation
            loss = loss_function(val_output_pc, val_gt_pc, device=device)
            val_loss += loss.detach().cpu() * val_input_pc.shape[0]

            # Error calculation
            val_count += val_input_pc.shape[0]

            # garbage collect
            val_input_pc = val_input_pc.detach().cpu()
            val_gt_pc = val_gt_pc.detach().cpu()
            val_output_pc = val_output_pc.detach().cpu()
            del (
                val_input_pc,
                val_gt_pc,
                val_output_pc,
            )
            gc.collect()
            torch.cuda.empty_cache()

        outstr = f"Validation Loss: {val_loss / val_count}"
        print(outstr, file=log_target)

        # Save the model
        if val_loss < best:
            best = val_loss
            print(f"Save model to ./models/{args.log}.pt", file=log_target)
            torch.save(model.state_dict(), f"./models/{args.log}.pt")

        log_target.flush()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=str,
        help="Input point cloud directory path",
    )
    parser.add_argument(
        "--reference",
        type=str,
        help="Reference point cloud directory path",
    )
    parser.add_argument(
        "--gt",
        type=str,
        help="Ground truth directory path",
    )
    parser.add_argument(
        "--r",
        type=int,
        default=4,
        help="Upsampling rate",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="Random seed",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print to stdout",
    )
    parser.add_argument(
        "--log",
        type=str,
        default="log",
        help="log file name",
    )
    parser.add_argument(
        "--num-epochs",
        type=int,
        default=100,
        help="Number of epochs",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        help="Batch size",
    )

    args = parser.parse_args()

    main(args)
